---
galaxy_info:
  author: Mateusz Trojak
  description: Installs and automatically configure TeamCity Agent.
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
    - name: Ubuntu
      versions:
        - bionic
  galaxy_tags:
    - system
    - development
    - teamcity
  dependencies:
    - ansiblebit.oracle-java
